#!/usr/bin/env python3
# This script takes the CSV file generated by the scraper and turns it into 
# a nice looking HTML page with a search bar and sorting.

import csv
import html
from collections import defaultdict
from pathlib import Path

# File settings
csv_file    = Path("data/itch_purchases.csv")
output_file = Path("itch_catalog.html")

# DataTables libraries (using CDNs so we don't have to download them)
css_link = "https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css"
jquery_js = "https://code.jquery.com/jquery-3.7.1.min.js"
datatables_js = "https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"

# Start building the HTML string
html_header = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Itch.io Game Library</title>
  <link rel="stylesheet" href="{css_link}">
  <style>
    body {{ font-family: sans-serif; padding: 20px; background: #fefefe; }}
    
    /* Make sure the table doesn't jump around */
    table {{ width: 100%; border-collapse: collapse; table-layout: fixed; }}
    
    /* Box size for the images */
    td img {{
      transition: transform 0.2s ease, box-shadow 0.2s ease;
      transform-origin: top left;
      position: relative;
      z-index: 1;
      cursor: zoom-in;
    }}
    
    /* Zoom effect on hover - makes it pop out to the right */
    td img:hover {{
      transform: scale(3.5);
      z-index: 9999;
      box-shadow: 5px 5px 15px rgba(0,0,0,0.3);
      border-radius: 4px;
      background-color: white;
    }}

    /* Styles for the little tag bubbles */
    .filter-chip {{
      display: inline-block;
      padding: 3px 8px;
      margin: 2px;
      border-radius: 12px;
      font-size: 0.85em;
      color: #222;
      text-decoration: none; /* No underline */
      border: 1px solid rgba(0,0,0,0.1); /* Subtle outline */
      transition: transform 0.1s, filter 0.1s;
    }}
    
    .filter-chip:hover {{
        transform: scale(1.05);
        filter: brightness(0.95);
        cursor: pointer;
    }}

    /* Rank Chip (The Number Bubble) */
    .rank-chip {{
      display: inline-block;
      padding: 2px 8px;
      border-radius: 12px;
      font-weight: bold;
      color: #444;
      border: 2px solid #ccc; /* Default, overridden inline */
      min-width: 30px;
      text-align: center;
      background-color: rgba(255,255,255,0.5);
    }}
    
    /* Description Styles - because reading 14k chars in a table cell is a crime */
    summary.desc-toggle {{
        cursor: pointer;
        color: #007bff;
        font-size: 0.85em;
        font-weight: bold;
        user-select: none;
        margin-top: 4px;
        display: inline-block;
    }}
    summary.desc-toggle:hover {{ text-decoration: underline; }}
    
    /* The scrollable box of doom */
    .desc-box {{
        margin-top: 6px;
        padding: 10px;
        background: #f8f9fa;
        border: 1px solid #e9ecef;
        border-radius: 4px;
        max-height: 250px; /* Stops the row from becoming 10 miles high */
        overflow-y: auto;
        white-space: pre-wrap; /* Keeps the newlines from the CSV */
        font-size: 0.9em;
        line-height: 1.5;
        color: #333;
        box-shadow: inset 0 2px 4px rgba(0,0,0,0.05);
    }}
    
    /* Hidden reset button */
    #clear-filter {{
      display: none;
      background-color: #ff4d4d;
      color: white;
      border: none;
      padding: 8px 16px;
      border-radius: 4px;
      cursor: pointer;
      font-weight: bold;
      margin-bottom: 10px;
    }}
    #clear-filter:hover {{ background-color: #cc0000; }}

    /* Alphabet Toolbar Styles */
    .alpha-bar {{
        margin-bottom: 15px;
        display: flex;
        flex-wrap: wrap;
        gap: 4px;
    }}
    .alpha-btn {{
        padding: 5px 10px;
        background: #eee;
        border: 1px solid #ddd;
        cursor: pointer;
        font-size: 0.9em;
        border-radius: 3px;
        min-width: 30px;
    }}
    .alpha-btn:hover {{ background: #ddd; }}
    .alpha-btn.active {{ background: #007bff; color: white; border-color: #0056b3; }}

    /* Page Jumper Input Style */
    .page-jump-container {{
        margin-right: 15px;
        font-size: 0.9em;
        color: #333;
        display: inline-block;
    }}
    .page-jump-input {{
        width: 50px;
        padding: 2px;
        margin-left: 5px;
        text-align: center;
        border: 1px solid #aaa;
        border-radius: 3px;
    }}
  </style>
</head>
<body>
<h1>Itch.io Game Library</h1>

<div class="alpha-bar" id="alpha-bar">
    </div>

<button id="clear-filter">Reset Filters</button>

<table id="games" class="display" style="width:100%">
  <thead>
    <tr>
      <th style="width: 100px;">Image</th> 
      <th style="width: auto;">Game Name</th>
      <th style="width: 120px;">Author</th>
      <th style="width: 85px;">Category</th>
      <th style="width: 100px;">Genre</th>
      <th style="width: 150px;">Tags</th>
      <th style="width: 90px;">Price</th>
      <th style="width: 50px;" title="Lower number = Oldest Acquisition">Added</th>
    </tr>
  </thead>
  <tbody>
"""

def get_pastel_color(text): # This was so unnecesary
    if not text: return "#eee"
    
    # Generate a hash from the string
    hash_val = 0
    for char in text:
        # Bitwise shift to mix up the bits based on the text content
        hash_val = ord(char) + ((hash_val << 5) - hash_val)
    
    # Extract RGB values from the hash
    r = (hash_val >> 0) & 0xFF
    g = (hash_val >> 8) & 0xFF
    b = (hash_val >> 16) & 0xFF
    
    # Mix with pure white (255) to ensure it is always pastel/light
    # Adjusting the math here changes how "washed out" the colors look
    r = int((r + 255) / 2)
    g = int((g + 255) / 2)
    b = int((b + 255) / 2)
    
    return f"#{r:02x}{g:02x}{b:02x}"

# 10 Colors for the Rank Gradient (0-9)
RANK_COLORS = [
    "#FF5252", # 0 Red
    "#FF7043", # 1 Orange
    "#FBC02D", # 2 Yellow/Gold
    "#66BB6A", # 3 Green
    "#26A69A", # 4 Teal
    "#00BCD4", # 5 Cyan
    "#42A5F5", # 6 Blue
    "#5C6BC0", # 7 Indigo
    "#AB47BC", # 8 Purple
    "#EC407A"  # 9 Pink
]

# Helper to calculate the Digital Root of a number
def get_digital_root(n):
    # I literally could have just used "n % 10" to get the last digit and it would have worked fine.
    # But instead I decided to implement Digital Roots because I watched a math video at 3am once.
    # Now your browser has to do recursion for every single row in the table. You're welcome.
    if n == 0: return 0
    while n > 9:
        n = sum(int(digit) for digit in str(n))
    return n

# The javascript magic for sorting and searching, This part of the code was shamelessly stolen from Brian, Thank you Brian.
# He made it to build a magic the gathering card database for his collection but It deserved a better home than MTG so here it is.
html_footer = f"""
    </tbody>
  </table>
  <script src="{jquery_js}"></script>
  <script src="{datatables_js}"></script>
  <script>
  $(document).ready(function(){{
    
    // --- SETUP ALPHABET BAR ---
    const bar = $('#alpha-bar');
    // Button for Symbols/Other (Start with anything NOT a-z or 0-9)
    bar.append(`<button class="alpha-btn" data-regex="^[^a-zA-Z0-9]">!.?</button>`);
    // Button for Numbers (Starts with 0-9)
    bar.append(`<button class="alpha-btn" data-regex="^[0-9]">0-9</button>`);
    // Buttons for A-Z
    const letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
    letters.forEach(l => {{
        bar.append(`<button class="alpha-btn" data-regex="^${{l}}">${{l}}</button>`);
    }});

    // Initialize DataTables
    const table = $('#games').DataTable({{
      orderCellsTop: true,
      fixedHeader: true,
      pageLength: 25,
      stripeClasses: [],
      rowCallback: function(row,data,index) {{
        // Zebra striping
        const bg = index % 2 === 0 ? '#ffffff' : '#f9f9f9';
        $(row).css('background-color', bg);
      }},
      // --- PAGE JUMPER LOGIC ---
      drawCallback: function() {{
          // Check if we need to add the input (target the pagination container)
          var paginate = $(this).closest('.dataTables_wrapper').find('.dataTables_paginate');
          
          if (paginate.length > 0 && paginate.find('.page-jump-input').length === 0) {{
             var info = this.api().page.info();
             
             // Create the input element
             var jumper = $('<span class="page-jump-container">Go to: <input type="number" class="page-jump-input" min="1" max="'+info.pages+'" value="'+(info.page+1)+'"></span>');
             
             // Prepend it so it sits to the left of the Prev/Next buttons
             paginate.prepend(jumper);
             
             // Bind the change event
             jumper.find('input').on('change keyup', function(e){{
                 // Only jump on Enter or Click-away, or if it's a valid number
                 if (e.type === 'keyup' && e.key !== 'Enter') return;
                 
                 var p = parseInt(this.value) - 1;
                 if (!isNaN(p) && p >= 0 && p < info.pages) {{
                     table.page(p).draw('page');
                 }}
             }});
          }} else {{
             // Just update the number if the input exists (e.g. user clicked Next)
             var info = this.api().page.info();
             paginate.find('.page-jump-input').val(info.page + 1);
          }}
      }},
      columnDefs: [{{
        targets: 6, // Price column sorting fix
        render: function(data,type) {{
          if (type==='sort' || type==='type') {{
            const cleaned = data.replace(/<[^>]+>/g,'').replace(/[^\d.]/g,'');
            return cleaned ? parseFloat(cleaned) : Infinity;
          }}
          return data;
        }}
      }},
      {{
        targets: 7, // Rank column sorting fix (strip HTML)
        render: function(data,type) {{
          if (type==='sort' || type==='type') {{
             // Grab just the number inside the span
             const num = data.replace(/<[^>]+>/g,'');
             return parseInt(num) || 0;
          }}
          return data;
        }}
      }}]
    }});

    // --- ALPHABET FILTER LOGIC ---
    $('.alpha-btn').on('click', function(){{
        // Highlight active button
        $('.alpha-btn').removeClass('active');
        $(this).addClass('active');

        let regex = $(this).data('regex');
        
        // Filter Column 1 (Game Name) using Regex
        // true (regex), false (smart search off)
        table.column(1).search(regex, true, false).draw();
        
        $('#clear-filter').show();
    }});

    // Create the input row at the top
    $('#games thead tr').clone(false).appendTo('#games thead');
    $('#games thead tr:eq(1) th').each(function(i){{
      $(this).removeClass('sorting sorting_asc sorting_desc');
      
      // No search on image column
      if (i === 0) {{
        $(this).html('');
      }}
      // Dropdown for Category (Column 3)
      else if (i === 3) {{
        const options = [
          "All", "Assets", "Book", "Comic",
          "N/A", "Other", "Physical game",
          "Soundtrack", "Tool"
        ];
        const select = $('<select style="width:100%"></select>')
          .append(options.map(o => `<option>${{o}}</option>`).join(''))
          .on('change', function(){{
            const val = this.value === "All" ? "" : this.value;
            if (table.column(i).search() !== val) {{
              table.column(i).search(val).draw();
            }}
            $('#clear-filter').show();
          }}).on('click', e => e.stopPropagation());
        $(this).html(select);
      }}
      // Checkbox for Paid items (Column 6)
      else if (i === 6) {{
        $(this).html('<label><input type="checkbox" id="paid-filter"/> Paid?</label>')
               .find('label').on('click', e => e.stopPropagation());
      }}
      // New "Added" Column (Column 7) - No Search Input needed
      else if (i === 7) {{
        $(this).html(''); 
      }}
      // Standard text search for everything else
      else {{
        const input = $('<input>', {{
          type: 'text', placeholder: 'Search...', style: 'width:100%'
        }});
        $(this).html(input).find('input')
          .on('input', function() {{ // Using 'input' event for instant updates
            if (table.column(i).search() !== this.value) {{
              table.column(i).search(this.value).draw();
            }}
            $('#clear-filter').show();
          }}).on('click', e => e.stopPropagation());
      }}
    }});

    // Clicking a tag/chip puts it in the filter
    $('#games tbody').on('click', '.filter-chip', function(e){{
      e.preventDefault();
      const term = $(this).text().trim();
      const col  = $(this).closest('td').index();
      const inp  = $('#games thead tr:eq(1) th').eq(col).find('input, select');
      if (inp.length) {{
        inp.val(term).trigger('change');
        // Manually trigger search for text inputs since 'change' mostly helps selects
        if(inp.is('input')) {{
            table.column(col).search(term).draw();
        }}
        $('#clear-filter').show();
      }}
    }});

    // Paid checkbox logic
    $('#games thead').on('change','#paid-filter',function(){{
      if (this.checked) {{
        // Regex to match anything that isn't "N/A"
        table.column(6).search('^(?!N/A$).*$',true,false).draw();
      }} else {{
        table.column(6).search('').draw();
      }}
      $('#clear-filter').show();
    }});

    // Reset button logic
    $('#clear-filter').on('click',function(){{
      $('#games thead tr:eq(1) th input[type=text]').val('');
      $('#games thead tr:eq(1) th select').val('All');
      $('#paid-filter').prop('checked',false).trigger('change');
      $('.alpha-btn').removeClass('active'); // Clear active alphabet
      table.search('').columns().search('').draw();
      $(this).hide();
    }});
  }});
  </script>
</body>
</html>
"""

# Helper to clean up strings
def safe_text(value):
    txt = (value or "").strip()
    return txt if txt else "N/A"

# Helper to make sure we don't break HTML with weird characters
def safe_html(value):
    return html.escape(value or "", quote=True)

# Helper to turn a comma list "horror, 2d" into clickable buttons
def make_chips(cell):
    if not cell or not cell.strip():
        return "N/A"
    
    tags = [t.strip() for t in cell.split(",") if t.strip()]
    if not tags:
        return "N/A"
        
    # Helper to Help build the HTML for each tag
    links = []
    for tag in tags:
        # Generate the unique color for this specific tag
        color = get_pastel_color(tag)
        
        # We inject the color directly into the style
        links.append(f'<a href="#" class="filter-chip" style="background-color: {color};">{safe_html(tag)}</a>')
        
    return " ".join(links)

def build_rows(path):
    # Groups games by name+link so we can handle duplicates since itch allows them (For some reason)
    groups = defaultdict(list)
    game_rank_map = {} # Stores the calculated rank for each game

    if not path.exists():
        return "<tr><td colspan='8'>Error: CSV file not found.</td></tr>"

    with path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        
        # WE NEED TO READ EVERYTHING FIRST TO ESTABLISH ORDER
        # Since CSV is Newest -> Oldest, we iterate BACKWARDS (Oldest -> Newest)
        all_rows = list(reader)
        
        current_rank = 1
        
        # Start from the bottom (Oldest purchase)
        for record in reversed(all_rows):
            name = record.get("Game Name", "").strip()
            link = record.get("Game Page Link", "").strip()
            key = (name, link)
            
            # If we haven't seen this game yet, assign it the current rank
            if key not in game_rank_map:
                game_rank_map[key] = current_rank
                current_rank += 1
            
            # If we HAVE seen it, we do nothing (skipping it). 
            # This preserves the rank from the first (oldest) time we saw it.
            
            # Add to groups for display
            groups[key].append(record)

    rows = []
    
    # Sort by game name alphabetically for the default view
    for (game_name, page_link), records in sorted(groups.items()):
        count = len(records)
        first = records[0] # Just use the first entry for info
        
        # Get the rank we calculated (this will be the oldest rank)
        rank_num = game_rank_map.get((game_name, page_link), 999999)
        
        # Calculate the index for the color array using Digital Root
        digit_index = get_digital_root(rank_num)
        border_col = RANK_COLORS[digit_index]

        # Create the visual chip
        rank_html = f'<span class="rank-chip" style="border-color: {border_col};">{rank_num}</span>'
        
        # IMPORTANT: Added loading="lazy" to prevent browser crash on large libraries over 600 items
        thumb_url = first.get("Thumbnail", "")
        if thumb_url:
            img = f'<img src="{thumb_url}" loading="lazy" alt="Game Thumbnail" style="max-width:120px; height:auto; border-radius:4px;">'
        else:
            img = ""

        # Handle titles, add count if we own multiple copies
        title = safe_html(game_name or "N/A")
        suffix = f" ({count})" if count > 1 else ""
        link = safe_html(page_link or "#")
        
        # Add the description drop-down
        description = safe_html(first.get("Description", ""))
        if description and description != "N/A":
            details_html = (
                f'<details style="margin-top:2px;">'
                f'<summary class="desc-toggle">Description</summary>'
                f'<div class="desc-box">{description}</div>'
                f'</details>'
            )
        else:
            details_html = ""
            
        title_cell = f'<a href="{link}" target="_blank">{title}{suffix}</a>{details_html}'

        # Draw the Rest of the Owl
        author   = safe_html(first.get("Author", ""))
        category = make_chips(first.get("Category", ""))
        genre    = make_chips(first.get("Genre", ""))
        tags     = make_chips(first.get("Tags", ""))
        price    = safe_text(first.get("Price", ""))

        # Create the table row
        # Added the 'rank_html' as the last column
        row_html = f"""
        <tr>
          <td>{img}</td>
          <td>{title_cell}</td>
          <td>{author}</td>
          <td>{category}</td>
          <td>{genre}</td>
          <td>{tags}</td>
          <td>{price}</td>
          <td style="text-align:center;">{rank_html}</td>
        </tr>
        """.rstrip()
        rows.append(row_html)

    return "\n".join(rows)

def main():
    # Combine everything and save
    full_html = html_header + build_rows(csv_file) + html_footer
    output_file.write_text(full_html, encoding="utf-8")
    print(f"Done! Interactive catalog written to {output_file}")

if __name__ == "__main__":
    main()
