#!/usr/bin/env python3
# This script takes the CSV file generated by the scraper and turns it into 
# a nice looking HTML page with a search bar and sorting.

import csv
import html
from collections import defaultdict
from pathlib import Path

# File settings
csv_file    = Path("data/itch_purchases.csv")
output_file = Path("itch_catalog.html")

# DataTables libraries (using CDNs so we don't have to download them)
css_link = "https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css"
jquery_js = "https://code.jquery.com/jquery-3.7.1.min.js"
datatables_js = "https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"

# Start building the HTML string
html_header = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Itch.io Game Library</title>
  <link rel="stylesheet" href="{css_link}">
  <style>
    body {{ font-family: sans-serif; padding: 20px; background: #fefefe; }}
    
    /* Make sure the table doesn't jump around */
    table {{ width: 100%; border-collapse: collapse; table-layout: fixed; }}
    
    /* Box size for the images */
    td img {{
      transition: transform 0.2s ease, box-shadow 0.2s ease;
      transform-origin: top left;
      position: relative;
      z-index: 1;
      cursor: zoom-in;
    }}
    
    /* Zoom effect on hover - makes it pop out to the right */
    td img:hover {{
      transform: scale(3.5);
      z-index: 9999;
      box-shadow: 5px 5px 15px rgba(0,0,0,0.3);
      border-radius: 4px;
      background-color: white;
    }}

    /* Styles for the little tag bubbles */
    .filter-chip {{
      display: inline-block;
      padding: 3px 8px;
      margin: 2px;
      border-radius: 12px;
      font-size: 0.85em;
      color: #222;
      text-decoration: none; /* No underline */
      border: 1px solid rgba(0,0,0,0.1); /* Subtle outline */
      transition: transform 0.1s, filter 0.1s;
    }}
    
    .filter-chip:hover {{
        transform: scale(1.05);
        filter: brightness(0.95);
        cursor: pointer;
    }}
    
    /* Hidden reset button */
    #clear-filter {{
      display: none;
      background-color: #ff4d4d;
      color: white;
      border: none;
      padding: 8px 16px;
      border-radius: 4px;
      cursor: pointer;
      font-weight: bold;
      margin-bottom: 10px;
    }}
    #clear-filter:hover {{ background-color: #cc0000; }}
  </style>
</head>
<body>
<h1>Itch.io Game Library</h1>

<button id="clear-filter">Reset Filters</button>

<table id="games" class="display" style="width:100%">
  <thead>
    <tr>
      <th style="width: 130px;">Image</th> 
      <th>Game Name</th>
      <th>Author</th>
      <th>Category</th>
      <th>Genre</th>
      <th>Tags</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
"""

def get_pastel_color(text): # This was so unnecesary
    if not text: return "#eee"
    
    # Generate a hash from the string
    hash_val = 0
    for char in text:
        # Bitwise shift to mix up the bits based on the text content
        hash_val = ord(char) + ((hash_val << 5) - hash_val)
    
    # Extract RGB values from the hash
    r = (hash_val >> 0) & 0xFF
    g = (hash_val >> 8) & 0xFF
    b = (hash_val >> 16) & 0xFF
    
    # Mix with pure white (255) to ensure it is always pastel/light
    # Adjusting the math here changes how "washed out" the colors look
    r = int((r + 255) / 2)
    g = int((g + 255) / 2)
    b = int((b + 255) / 2)
    
    return f"#{r:02x}{g:02x}{b:02x}"

# The javascript magic for sorting and searching, This part of the code was shamelessly stolen from Brian, Thank you Brian.
# He made it to build a magic the gathering card database for his collection but It deserved a better home than MTG so here it is.
html_footer = f"""
    </tbody>
  </table>
  <script src="{jquery_js}"></script>
  <script src="{datatables_js}"></script>
  <script>
  $(document).ready(function(){{
    // Initialize DataTables
    const table = $('#games').DataTable({{
      orderCellsTop: true,
      fixedHeader: true,
      pageLength: 25,
      stripeClasses: [],
      rowCallback: function(row,data,index) {{
        // Zebra striping
        const bg = index % 2 === 0 ? '#ffffff' : '#f9f9f9';
        $(row).css('background-color', bg);
      }},
      columnDefs: [{{
        targets: 6, // Price column sorting fix
        render: function(data,type) {{
          if (type==='sort' || type==='type') {{
            const cleaned = data.replace(/<[^>]+>/g,'').replace(/[^\d.]/g,'');
            return cleaned ? parseFloat(cleaned) : Infinity;
          }}
          return data;
        }}
      }}]
    }});

    // Create the input row at the top
    $('#games thead tr').clone(false).appendTo('#games thead');
    $('#games thead tr:eq(1) th').each(function(i){{
      $(this).removeClass('sorting sorting_asc sorting_desc');
      
      // No search on image column
      if (i === 0) {{
        $(this).html('');
      }}
      // Dropdown for Category (Column 3)
      else if (i === 3) {{
        const options = [
          "All", "Assets", "Book", "Comic",
          "N/A", "Other", "Physical game",
          "Soundtrack", "Tool"
        ];
        const select = $('<select style="width:100%"></select>')
          .append(options.map(o => `<option>${{o}}</option>`).join(''))
          .on('change', function(){{
            const val = this.value === "All" ? "" : this.value;
            if (table.column(i).search() !== val) {{
              table.column(i).search(val).draw();
            }}
            $('#clear-filter').show();
          }}).on('click', e => e.stopPropagation());
        $(this).html(select);
      }}
      // Checkbox for Paid items (Column 6)
      else if (i === 6) {{
        $(this).html('<label><input type="checkbox" id="paid-filter"/> Paid?</label>')
               .find('label').on('click', e => e.stopPropagation());
      }}
      // Standard text search for everything else
      else {{
        const input = $('<input>', {{
          type: 'text', placeholder: 'Search...', style: 'width:100%'
        }});
        $(this).html(input).find('input')
          .on('input', function() {{ // Using 'input' event for instant updates
            if (table.column(i).search() !== this.value) {{
              table.column(i).search(this.value).draw();
            }}
            $('#clear-filter').show();
          }}).on('click', e => e.stopPropagation());
      }}
    }});

    // Clicking a tag/chip puts it in the filter
    $('#games tbody').on('click', '.filter-chip', function(e){{
      e.preventDefault();
      const term = $(this).text().trim();
      const col  = $(this).closest('td').index();
      const inp  = $('#games thead tr:eq(1) th').eq(col).find('input, select');
      if (inp.length) {{
        inp.val(term).trigger('change');
        // Manually trigger search for text inputs since 'change' mostly helps selects
        if(inp.is('input')) {{
            table.column(col).search(term).draw();
        }}
        $('#clear-filter').show();
      }}
    }});

    // Paid checkbox logic
    $('#games thead').on('change','#paid-filter',function(){{
      if (this.checked) {{
        // Regex to match anything that isn't "N/A"
        table.column(6).search('^(?!N/A$).*$',true,false).draw();
      }} else {{
        table.column(6).search('').draw();
      }}
      $('#clear-filter').show();
    }});

    // Reset button logic
    $('#clear-filter').on('click',function(){{
      $('#games thead tr:eq(1) th input[type=text]').val('');
      $('#games thead tr:eq(1) th select').val('All');
      $('#paid-filter').prop('checked',false).trigger('change');
      table.columns().search('').draw();
      $(this).hide();
    }});
  }});
  </script>
</body>
</html>
"""

# Helper to clean up strings
def safe_text(value):
    txt = (value or "").strip()
    return txt if txt else "N/A"

# Helper to make sure we don't break HTML with weird characters
def safe_html(value):
    return html.escape(value or "", quote=True)

# Helper to turn a comma list "horror, 2d" into clickable buttons
def make_chips(cell):
    if not cell or not cell.strip():
        return "N/A"
    
    tags = [t.strip() for t in cell.split(",") if t.strip()]
    if not tags:
        return "N/A"
        
    # Helper to Help build the HTML for each tag
    links = []
    for tag in tags:
        # Generate the unique color for this specific tag
        color = get_pastel_color(tag)
        
        # We inject the color directly into the style
        links.append(f'<a href="#" class="filter-chip" style="background-color: {color};">{safe_html(tag)}</a>')
        
    return " ".join(links)

def build_rows(path):
    # Groups games by name+link so we can handle duplicates since itch allows them (For some reason)
    groups = defaultdict(list)

    if not path.exists():
        return "<tr><td colspan='7'>Error: CSV file not found.</td></tr>"

    with path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for record in reader:
            # Create a unique key for the game
            name = record.get("Game Name", "").strip()
            link = record.get("Game Page Link", "").strip()
            groups[(name, link)].append(record)

    rows = []
    
    # Sort by game name
    for (game_name, page_link), records in sorted(groups.items()):
        count = len(records)
        first = records[0] # Just use the first entry for info
        
        # IMPORTANT: Added loading="lazy" to prevent browser crash on large libraries over 600 items
        thumb_url = first.get("Thumbnail", "")
        if thumb_url:
            img = f'<img src="{thumb_url}" loading="lazy" alt="Game Thumbnail" style="max-width:120px; height:auto; border-radius:4px;">'
        else:
            img = ""

        # Handle titles, add count if we own multiple copies
        title = safe_html(game_name or "N/A")
        suffix = f" ({count})" if count > 1 else ""
        link = safe_html(page_link or "#")
        
        # Add the description drop-down
        description = safe_html(first.get("Description", ""))
        if description and description != "N/A":
            details_html = (
                f'<details style="margin-top:4px;"><summary style="cursor:pointer;">Description</summary>'
                f'<div style="margin-top:6px; white-space:pre-wrap; font-size:0.9em; line-height:1.4;">{description}</div></details>'
            )
        else:
            details_html = ""
            
        title_cell = f'<a href="{link}" target="_blank">{title}{suffix}</a>{details_html}'

        # Draw the Rest of the Owl
        author   = safe_html(first.get("Author", ""))
        category = make_chips(first.get("Category", ""))
        genre    = make_chips(first.get("Genre", ""))
        tags     = make_chips(first.get("Tags", ""))
        price    = safe_text(first.get("Price", ""))

        # Create the table row
        row_html = f"""
        <tr>
          <td>{img}</td>
          <td>{title_cell}</td>
          <td>{author}</td>
          <td>{category}</td>
          <td>{genre}</td>
          <td>{tags}</td>
          <td>{price}</td>
        </tr>
        """.rstrip()
        rows.append(row_html)

    return "\n".join(rows)

def main():
    # Combine everything and save
    full_html = html_header + build_rows(csv_file) + html_footer
    output_file.write_text(full_html, encoding="utf-8")
    print(f"Done! Interactive catalog written to {output_file}")

if __name__ == "__main__":
    main()
